services:
  - type: web
    name: blog-kumar
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn my_site.wsgi:application"
    runtime:
      python: 3.10.13  # 👈 Force compatible Python version
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: my_site.settings
      - key: SECRET_KEY
        value: igd3-km9f)4m_+965am6xh0#8g8q&76a)c%m6t_km@l3^kydzp
      - key: DEBUG
        value: False
      - key: CLOUDINARY_CLOUD_NAME
        value: dfre000b8
      - key: CLOUDINARY_API_KEY
        value: 149284517355592
      - key: CLOUDINARY_API_SECRET
        value: 1KIv6eNkShrU0qaVmiOzFyShHng
